<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="bigBoyTestReport" duration-ms="3347" started-at="2020-11-09T07:32:37Z" finished-at="2020-11-09T07:32:41Z">
    <groups>
    </groups>
    <test name="bigBoyTestReport" duration-ms="3347" started-at="2020-11-09T07:32:37Z" finished-at="2020-11-09T07:32:41Z">
      <class name="bigBoy.app.infromTest">
        <test-method status="FAIL" signature="addInformChannelTest()[pri:1, instance:bigBoy.app.infromTest@436e852b]" name="addInformChannelTest" duration-ms="440" started-at="2020-11-09T15:32:40Z" finished-at="2020-11-09T15:32:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SUCCESS] but found [NO_LOGIN]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [NO_LOGIN]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at bigBoy.app.infromTest.addInformChannelTest(infromTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addInformChannelTest -->
      </class> <!-- bigBoy.app.infromTest -->
      <class name="bigBoy.app.loginTest">
        <test-method status="PASS" signature="sendSecurityCodeTest()[pri:1, instance:bigBoy.app.loginTest@1a1d6a08]" name="sendSecurityCodeTest" duration-ms="2891" started-at="2020-11-09T15:32:37Z" finished-at="2020-11-09T15:32:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendSecurityCodeTest -->
      </class> <!-- bigBoy.app.loginTest -->
    </test> <!-- bigBoyTestReport -->
  </suite> <!-- bigBoyTestReport -->
</testng-results>
